### ISSUE TITLE
[CRITICAL] Search problem

### ISSUE THREAD

**Issue by arosier10** [ProtonMail/rdash-angular#15]
1) Search an outside email address
2) If the email address is in the waiting list but not as a notification email address in the created account it only displays the waiting list information. 

Expected:

Search outside email address:
This queries to see if there are any usernames associated with that email address, then a query is performed to see if there are any active accounts under that username. Both the active account and waiting list entry are shown

**Comment by bartbutler** [comment]
Redone and live
